alter table SAMLADDON_SAML_CONNECTION alter column KEYSTORE_PASSWORD rename to KEYSTORE_PASSWORD__U32795 ^
alter table SAMLADDON_SAML_CONNECTION alter column KEYSTORE_LOGIN rename to KEYSTORE_LOGIN__U72224 ^
alter table SAMLADDON_SAML_CONNECTION alter column KEYSTORE_ID rename to KEYSTORE_ID__U61132 ^
drop index IDX_SAMLADDON_SAML_CONNECTION_ON_KEYSTORE ;
alter table SAMLADDON_SAML_CONNECTION drop constraint FK_SAMLADDON_SAML_CONNECTION_ON_KEYSTORE ;
alter table SAMLADDON_SAML_CONNECTION add column KEYSTORE_ID varchar(36) ;
