alter table SAMLADDON_SAML_CONNECTION add IDP_METADATA_ID varchar2(32);

alter table SAMLADDON_SAML_CONNECTION add constraint FK_SAML_IDP_METADATA foreign key (IDP_METADATA_ID) references SYS_FILE(ID);
create index IDX_SAML_IDP_METADATA on SAMLADDON_SAML_CONNECTION (IDP_METADATA_ID);